language: node_js
script:
- npm test
- npm run browser-test-ff
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
sudo: false
node_js:
- '0.12'
env:
  global:
    secure: ED+05KdMKREJdP8doskLsejnN0KnqES6o8g3juRwRWnwWoa6E+NJGv34ayxIf+2q/XI6ReWVwIkQkhlw4m/nLO06SPISGQtHkYBe1xHDqpM/BoB7XMxN/znFe+vB//AX8TTK1Pk7hC0BuSd2728fcsROHZCqxwiy723WPRnf2Gs=
